mikrotik-pkg_secrets:
  config_params:
    mikrotik-pkg/_stack/routeros/example-lab:
      _provider_routeros_password: ENC[AES256_GCM,data:tcs5M+BxaqbK6lu4U7VCCA==,iv:OYv3SxfsXBjKFjCE6tvAGNcw1fh9rVwJ2whPyt5bXaY=,tag:MrcB7yvn5hxtQNHD9QmcoA==,type:str]
      _provider_routeros_username: ENC[AES256_GCM,data:PhjPeRc=,iv:g8cw/W5g8w/cgjjib+GL0MAXZPAsFEqRYVSNGhHHxi4=,tag:po6zRZ3wr/IMl/CwosPhrQ==,type:str]
sops:
  lastmodified: "2026-04-14T15:37:14Z"
  mac: ENC[AES256_GCM,data:ysxG7/9MFDci+1Vrq/HIe0i7TpOc1IuJvLa3L1vYb7Dn3Ip+bkeMGpzVJFJrvU1Lb184SEvb4sTB3PEfHDMwbgpVESnSAJRwEX2tl8XlZVm4zYaSOq0dlZM4Yy9Zup6WgZfn77BMa743RCcTZhCofK+qF59mKM99ti0QRQGsmVQ=,iv:JVmX9ReudEfNobAcWaX6g+winOLWT9xyfumvW4r/Qn4=,tag:WjuSmRqthqzTJkuEtg/yfA==,type:str]
  pgp:
    - created_at: "2026-04-14T15:37:14Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQGMAweuHx4I2A4UAQv/aQetXiW/W+8GNdQDuj6VrFm76W3XiaevJ84fMBgnsnb2
        eJitXKfL1dZGKyDZOfJ9ComLStgahwEc8BOhkcymG9PPfrL8z+FEzBVtJfB9TG09
        4iS4PWIEVr0/N/3IpAoa8a0LmMppHPcE+YHA6uNLXjAxpchO9W/qJNTutq7n9T54
        Um90Ypr9fwguSeWNVA0q89TMRaxp8JcjLXKun1SHBADdZhq23ml8VO5dYsxrMhuv
        q5vsmSGUO19XZOuQMe6Y4jY3h0zlhlr7fLNolfMIBJxFWrQdbrW9LlkWXlRrKNUy
        wlPfJ+Xv1pCdYnso64vH4SCp/Q3QsCKuV72MM5uasSTIr+E3chWttIirVkzuzCze
        wanlNFrpRDYE/f+NIQ3/7RHWoeSiPsusJQQgqd6BCF4FpeYP+40kMLb/juDSYc8p
        TlysqT4xWiH4Rvfr8nona2X23AlvYKsRlvP6snFwyN1nd75SSvjbJVICqWMIE7eJ
        GaahdFRW4FqQExf/HB770l4BBsicUbqUiAwAuV4HVZ3zoRsIw06oe3Omv6gyjoRY
        Gv1cFyN3SOe6yqF5NHpA3Z/YoDpaKYlxw0UzUsewrMxewhINvGXEfztfzg3LlHWF
        X59IZTjzMgXS2WWWLLb3
        =CfVX
        -----END PGP MESSAGE-----
      fp: 446B4127CF4E00C389579F20986E9FAE2FB2BEBD
    - created_at: "2026-04-14T15:37:14Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA1MQLyG6dlTlARAAyycw+QTZg60hVLbgmpQdxRQkQyMQlT6d9c8XCIm7FOwX
        9TS0ykCwqlqGOYHWFY++mS4PyK4/CHY/VbrQegxwcugqIK84GZBEULHzPx6irnTF
        5ZVE6Nu4L6WvQCMtKOEMIXKlcyi4Z0HAktvEygX9Ya9Ipadn7l6ZFkRTjv3ISgXv
        nu/tCizq0O8XefN2soE1AdT+NX6bvdqhAvoAKy0q5Wi5m5z5Xnovr5EW6G/NtdlH
        0I32dsAtffYaLJ/Pc/RDjxV4VQy0axbT4+OjZlzMiunqs5VYO/n85CUtS8S8vSZQ
        s5u1TqTMxlnZEATT+hK4BR6jpP8okYSndvz1LGlmyVP+g8A+xHxocrGfXTdkOgKO
        zX3gWDn77EkGDRJG1ZGk7nFTACRL0tWn/FrWfsRkjtUgeabRQ2euoOfrCU7dWKq9
        SKDzfknNl5cwixCjGra3T3UCCzZmy+lHWZY5pWgZsjDWoM4bj2zT2rd87ySVaP2D
        FeRMM+7YT08ohnCO9nAjaXky4+JbTtc0469f/eLBkjILRs62u7WNYQga9erRoWlC
        4pHqXZHbKtsvrg+3lGhPWPazrG6yTXQrDB9l5s2m6D4NhfjqWRi5W9DSQiIp3HYr
        usM+9t481C+qlfDQSEWjxfwMMI4vRRkRd4GwYYP1OutHEUSwOhEO9IuMVGLK1pDS
        XgG4vrgZVSa9PxK5UIWIE/0y4EQy64DHqsN0s/Fw+9nZtoRZZK97HMEMhUrQ8WM7
        5ac0zWfcZQ5P9Fm9Jn8X6zHetwqhXnV3HPHrwYSJzL6gC9Tx9Q91b4PzRlnOjgU=
        =WMV5
        -----END PGP MESSAGE-----
      fp: 1FAFFDF2C76C758F736178E2B776DF4CEB6B692B
  unencrypted_suffix: _unencrypted
  version: 3.10.2
